### ISSUE TITLE
404 Chat

### ISSUE THREAD

**Issue by cprogrammer1994** [OSSRomania/membri#2]
broken link (gitter)

Gitter
404. This is not the chat you're looking for. Sorry. :(

**Comment by IonicaBizau** [comment]
Trebuie să fii autentificat pe [`gitter.im`](https://gitter.im/)—iar apoi poți accesa [`OSSRomania/main`](https://gitter.im/OSSRomania/main). 🚀 

/cc https://github.com/gitterHQ/gitter/issues/1340
